sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20031020
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: web-tlias-nuo

spring:
  redis:
    password: root
    database: 0
    port: 6379
    host: 192.168.6.102
  wechat:
    appid: wx9e8dde9d2df9df58
    secret: 7a354c0cab2186281c18839acf453e37
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php